name: Build only

on:
  pull_request:
    branches:
      - master

jobs:
  build-windows:
    uses: ./.github/workflows/workflow-build-windows.yaml
  build-macos:
    uses: ./.github/workflows/workflow-build-macos.yaml
  build-ubuntu:
    uses: ./.github/workflows/workflow-build-ubuntu.yaml
  build:
    name: Create packages automatically on pull request
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-ubuntu]
