name: Nightly

on:
  push:
    branches:
      - master

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  build-windows:
    uses: ./.github/workflows/workflow-build-windows.yaml
  build-macos:
    uses: ./.github/workflows/workflow-build-macos.yaml
  build-ubuntu:
    uses: ./.github/workflows/workflow-build-ubuntu.yaml
  nightly:
    name: Release packages automatically on push
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-ubuntu]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Get variables
        id: get-targets
        run: |
          find . -print
          windows_path=$(find . -maxdepth 1 -type d -name "openmsx-debugger-windows-*" -printf %f)
          echo "windows_path=$windows_path" >> $GITHUB_OUTPUT
          if [ "$windows_path" = "" ]; then
            echo "Windows package not found"
            exit 1
          fi
          macos_path=$(find . -maxdepth 1 -type d -name "openmsx-debugger-macos-*" -printf %f)
          echo "macos_path=$macos_path" >> $GITHUB_OUTPUT
          if [ "$macos_path" = "" ]; then
            echo "Mac OS package not found"
            exit 1
          fi
          ubuntu_path=$(find . -maxdepth 1 -type d -name "openmsx-debugger-ubuntu-*" -printf %f)
          echo "ubuntu_path=$ubuntu_path" >> $GITHUB_OUTPUT
          if [ "$ubuntu_path" = "" ]; then
            echo "Ubuntu package not found"
            exit 1
          fi
      - name: Package Windows binaries as zip files
        run: |
          # Windows packaging
          cd ${{ steps.get-targets.outputs.windows_path }}
          zip "${{ steps.get-targets.outputs.windows_path }}.zip" -r .
          cd ..
          mv ${{ steps.get-targets.outputs.windows_path }}/${{ steps.get-targets.outputs.windows_path }}.zip .
      - name: Package Ubuntu binaries as tbz files
        run: |
          # Ubuntu packaging
          cd "${{ steps.get-targets.outputs.ubuntu_path }}"
          tar cvfj "/tmp/${{ steps.get-targets.outputs.ubuntu_path }}.tbz" .
      - name: Package Mac OS binaries as tbz files
        run: |
          # Mac OS packaging
          tar cvfj "/tmp/${{ steps.get-targets.outputs.macos_path }}.tbz" "${{ steps.get-targets.outputs.macos_path }}"

  release:
    runs-on: ubuntu-latest
    needs: nightly
    steps:
      - name: Create info file
        run: |
          echo "ref: ${GITHUB_REF}" > info.txt
          echo "commit: ${GITHUB_SHA}" >> info.txt
          echo "build: $(date +"%Y-%m-%dT%H:%M:%SZ")" >> info.txt

      - name: Update nightly release
        uses: eine/tip@master
        with:
          tag: nightly
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: info.txt /tmp/*.tbz

