name: Build workflow

on:
  workflow_call:

env:
  package_origin: gh

jobs:
  build-on-macos:
    runs-on: macos-latest
    name: Mac OS builder
    steps:
    - name: Configure base system
      run: |
        git config --global init.defaultBranch master
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Compile repository code
      id: compile
      shell: bash
      run: |
        brew install qt@5
        path=derived/openMSX_Debugger.app
        echo "path=$path" >> $GITHUB_OUTPUT
        echo "name=openmsx-debugger-macos-${{ env.package_origin }}" >> $GITHUB_OUTPUT
        make
    - name: Upload redistributable package for Mac OS
      uses: actions/upload-artifact@v3
      with:
        name: openmsx-debugger-macos-${{ env.package_origin }}
        path: |
          ${{ steps.compile.outputs.path }}

